Category = document.getElementById('category'); 
Category.addOption = function(value, name) {
    n = document.createElement('option');
    n.setAttribute('value',value);
    n.innerText = name;
    this.appendChild(n);
};
Category.addOption('','--カテゴリーを選択してください--');
Category.addOption('0','Windows');
Category.addOption('1','Key Combination');
Category.addOption('2','Application');
Category.addOption('3','Mouse');
Category.addOption('4','Mouse with Key');
Category.addOption('5','Key');

Action = document.getElementById('action');
Action.addOption = function(value, name) {
    n = document.createElement('option');
    n.setAttribute('value',value);
    n.innerText = name;
    this.appendChild(n);
};
Category.addEventListener('change', (e)=>{
Action.innerText = '';
switch(e.target.value) {
case '0':
Action.addOption('1','Minimize Window ');
Action.addOption('5','Maximize Window ');
Action.addOption('15','Switch to next Window ');
Action.addOption('51','Start Screen Saver ');
Action.addOption('191','Win8 Charm ');
break;
case '1':
Action.addOption('17','Ctrl + Win ');
Action.addOption('146','Alt + Left Key ');
Action.addOption('147','Alt + Right Key ');
Action.addOption('148','Alt + Up Key ');
Action.addOption('149','Alt + Down Key ');
Action.addOption('150','Shift + Left Key ');
Action.addOption('151','Shift + Right Key ');
Action.addOption('152','Shift + Up Key ');
Action.addOption('153','Shift + Down Key ');
Action.addOption('4638','Ctrl+O ');
Action.addOption('11550','Ctrl+C ');
Action.addOption('4894','Ctrl+P ');
Action.addOption('11806','Ctrl+V ');
Action.addOption('12062','Ctrl+H ');
Action.addOption('1822','Ctrl+W ');
Action.addOption('286','Alt + Tab Key ');
Action.addOption('542','Alt + Esc Key ');
Action.addOption('798','Alt + Backspace Key ');
Action.addOption('1054','Shift + Backspace Key ');
Action.addOption('1310','Alt + Enter Key ');
Action.addOption('1566','Alt + F4 Key ');
Action.addOption('2078','Alt + Home Key ');
Action.addOption('2590','Ctrl + Esc Key ');
Action.addOption('2846','Left Shift Key ');
Action.addOption('3358','Shift + Up Key ');
Action.addOption('3614','Shift + Down Key ');
Action.addOption('3614','Shift + Down Key ');
Action.addOption('3870','Shift + Tab Key ');
Action.addOption('4126','Shift + > Key ');
Action.addOption('4382','Shift + < Key ');
Action.addOption('5406','Alt + Print Scr Key ');
Action.addOption('5662','Ctrl + Print Scr Key ');
Action.addOption('5918','Ctrl + Tab Key ');
Action.addOption('6174','Ctrl + F4 Key ');
Action.addOption('6430','Ctrl + PageUp Key ');
Action.addOption('6686','Ctrl + PageDown Key ');
Action.addOption('6942','Ctrl + \'+\' Key ');
Action.addOption('7198','Ctrl + \'-\'  Key ');
Action.addOption('8990','Win + D Key ');
Action.addOption('9246','Win + Tab Key ');
break;
case '2':
Action.addOption('53','CD Tray Open ');
Action.addOption('54','CD Tray Close ');
Action.addOption('20510','MPlayer Play ');
Action.addOption('20766','MPlayer Stop ');
Action.addOption('21790','MPlayer FWD ');
Action.addOption('22046','MPlayer RWD ');
Action.addOption('17950','MPlayer Pause/Start ');
Action.addOption('17694','Synapse Zoom reset ');
Action.addOption('13854','iTunes Vol. Up ');
Action.addOption('14110','iTunes Vol. Down ');
Action.addOption('14366','iTunes Prev Tune ');
Action.addOption('14622','iTunes Next Tune ');
Action.addOption('14878','iTunes Prev Album ');
Action.addOption('15134','iTunes Next Album ');
Action.addOption('15390','iTunes Full screen ');
Action.addOption('15646','iTunes Mute ');
Action.addOption('15902','Adobe ZoomIn ');
Action.addOption('16158','Adobe ZoomOut ');
Action.addOption('16414','Adobe AutoScroll ');
Action.addOption('16670','Adobe AutoFull ');
Action.addOption('16926','Adobe Home ');
Action.addOption('17182','Adobe Turn Right ');
Action.addOption('17438','Adobe Turn Left ');
Action.addOption('22302','Skype Call ');
Action.addOption('22558','Skype Video Call ');
Action.addOption('22814','Skype Dial ');
Action.addOption('23070','Skype Answer ');
Action.addOption('23326','Skype Video Answer ');
Action.addOption('24094','Skype HangUp ');
Action.addOption('143','Chrome Open Bookmark ');
Action.addOption('144','Chrome Add to BookMark ');
Action.addOption('145','Chrome Open Menu ');
Action.addOption('23582','PhotoViewer L ');
Action.addOption('24350','Google Voice ');
Action.addOption('23838','PhotoViewer R');
break;
case '3':
Action.addOption('76','Drag Left with Right button ');
Action.addOption('77','Drag Right with Right button ');
Action.addOption('78','Drag Down with Right button ');
Action.addOption('79','Drag Up with Right button ');
Action.addOption('100','Cursor Up ');
Action.addOption('101','Cursor Down ');
Action.addOption('102','Cursor Right ');
Action.addOption('103','Cursor Left ');
Action.addOption('104','Mouse Wheel + ');
Action.addOption('105','Mouse Wheel - ');
Action.addOption('110','Cursor to Center ');
Action.addOption('106','Drag Up ');
Action.addOption('107','Drag Down ');
Action.addOption('108','Drag Right ');
Action.addOption('109','Drag Left ');
Action.addOption('111','Left Click ');
Action.addOption('112','Right Click ');
Action.addOption('113','Double Click ');
break;
case '4':
Action.addOption('80','Drag Left with Right button+Shift ');
Action.addOption('81','Drag Right with Right button+Shift ');
Action.addOption('82','Drag Down with Right button+Shift ');
Action.addOption('83','Drag Up with Right button+Shift ');
Action.addOption('84','Drag Up with Shift Key ');
Action.addOption('85','Drag Down with Shift Key ');
Action.addOption('86','Drag Right with Shift Key ');
Action.addOption('87','Drag Left with Shift Key ');
Action.addOption('92','Drag Up with Ctrl Key ');
Action.addOption('93','Drag Down with Ctrl Key ');
Action.addOption('94','Drag Right with Ctrl Key ');
Action.addOption('95','Drag Left with Ctrl Key ');
Action.addOption('88','Drag Up with Alt+Ctrl Key ');
Action.addOption('89','Drag Down with Alt+Ctrl Key ');
Action.addOption('90','Drag Right with Alt+Ctrl Key ');
Action.addOption('91','Drag Left with Alt+Ctrl Key ');
Action.addOption('96','Drag Up width Alt key ');
Action.addOption('97','Drag Down width Alt key ');
Action.addOption('98','Drag Right with Alt Key ');
Action.addOption('99','Drag Left with Alt Key ');
break;
case '5':
Action.addOption('132','Key Up ');
Action.addOption('133','Key Down ');
Action.addOption('130','Key Right ');
Action.addOption('131','Key Left ');
Action.addOption('159','Alt Key ');

Action.addOption('134','Key Page Up ');
Action.addOption('135','Key Page Down ');
Action.addOption('136','Space Key ');
Action.addOption('140','Enter Key ');
Action.addOption('141','Esc Key ');
Action.addOption('154','Press Alt Key ');
Action.addOption('155','Tab Key ');
Action.addOption('156','Press Ctrl Key ');
Action.addOption('157','Press Shift Key ');
Action.addOption('200','Key 0 ');
Action.addOption('201','Key 1 ');
Action.addOption('202','Key 2 ');
Action.addOption('203','Key 3 ');
Action.addOption('204','Key 4 ');
Action.addOption('205','Key 5 ');
Action.addOption('206','Key 6 ');
Action.addOption('207','Key 7 ');
Action.addOption('208','Key 8 ');
Action.addOption('209','Key 9 ');
Action.addOption('61','Key F1 ');
Action.addOption('62','Key F2 ');
Action.addOption('63','Key F3 ');
Action.addOption('64','Key F4 ');
Action.addOption('65','Key F5 ');
Action.addOption('66','Key F6 ');
Action.addOption('67','Key F7 ');
Action.addOption('68','Key F8 ');
Action.addOption('69','Key F9 ');
Action.addOption('70','Key F10 ');
Action.addOption('71','Key F11 ');
Action.addOption('72','Key F12 ');
Action.addOption('165','End Key ');
Action.addOption('166','Key + ');
Action.addOption('167','Key - ');
Action.addOption('168','Key N ');
Action.addOption('169','Key P ');
Action.addOption('170','Key Q ');
Action.addOption('171','Key Z ');
Action.addOption('172','Key M ');
Action.addOption('173','Key F ');
Action.addOption('174','Key R ');
Action.addOption('175','Key X ');
Action.addOption('176','Key W ');
Action.addOption('177','Key A ');
Action.addOption('178','Key S ');
Action.addOption('179','Key D ');
Action.addOption('175','Key X ');
Action.addOption('163','Key Z ');
Action.addOption('3102','Right Shift Key ');
Action.addOption('55','Left SHIFT Key ');
Action.addOption('56','Right SHIFT Key ');
Action.addOption('57','Left CTRL Key ');
Action.addOption('58','Right CTRL Key ');
Action.addOption('5150','Print Scr Key ');
Action.addOption('7710','Windows Key ');
break;
}
});